services:
  redis:
    image: redis:alpine
    networks:
      - connection

  backend:
    image: aniadampashut/ctfs:wello
    environment:
      REDIS_URL: redis:6379
    ports:
      - "8080:8080"
    networks:
      - connection



networks:
  # The presence of these objects is sufficient to define them
  connection: {}